{% set version = "2.0-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-compositions
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/compositions_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/compositions/compositions_{{ version }}.tar.gz
  sha256: 19cb515e5e61348c1f3672c8d00e8c3491c84774716729e62559e0948c255d77

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bayesm
    - r-robustbase
    - r-tensora
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-bayesm
    - r-robustbase
    - r-tensora

test:
  commands:
    - $R -e "library('compositions')"           # [not win]
    - "\"%R%\" -e \"library('compositions')\""  # [win]

about:
  home: http://www.stat.boogaart.de/compositions
  license: GPL-2.0-or-later
  summary: Provides functions for the consistent analysis of compositional data (e.g. portions of substances) and positive numbers (e.g. concentrations) in the way proposed by J. Aitchison and V. Pawlowsky-Glahn.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo

# Package: compositions
# Version: 1.40-3
# Date: 2019-11-25
# Title: Compositional Data Analysis
# Author: K. Gerald van den Boogaart <boogaart@hzdr.de>, Raimon Tolosana-Delgado, Matevz Bren
# Maintainer: K. Gerald van den Boogaart <support@boogaart.de>
# Depends: R (>= 2.2.0), tensorA, robustbase, bayesm
# Suggests: rgl,combinat, energy
# Description: Provides functions for the consistent analysis of compositional data (e.g. portions of substances) and positive numbers (e.g. concentrations) in the way proposed by J. Aitchison and V. Pawlowsky-Glahn.
# License: GPL (>= 2)
# URL: http://www.stat.boogaart.de/compositions
# NeedsCompilation: yes
# Packaged: 2019-10-25 13:41:53 UTC; tolosa53
# Repository: CRAN
# Date/Publication: 2019-10-25 15:20:02 UTC
