{% set version = "2.0-8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-compositions
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/compositions_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/compositions/compositions_{{ version }}.tar.gz
  sha256: c5063488f456992b5821458b3237322addffd3451ae91f9474707886971ef290

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-bayesm                   # [build_platform != target_platform]
    - r-tensora                  # [build_platform != target_platform]
    - r-mass                     # [build_platform != target_platform]
    - r-robustbase               # [build_platform != target_platform]
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-bayesm                   # [build_platform != target_platform]
    - r-mass                     # [build_platform != target_platform]
    - r-robustbase               # [build_platform != target_platform]
    - r-tensora                  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-bayesm
    - r-mass
    - r-robustbase
    - r-tensora
    - libblas
    - liblapack
  run:
    - r-base
    - r-bayesm
    - r-mass
    - r-robustbase
    - r-tensora

test:
  commands:
    - $R -e "library('compositions')"           # [not win]
    - "\"%R%\" -e \"library('compositions')\""  # [win]

about:
  home: http://www.stat.boogaart.de/compositions
  license: GPL-2.0-or-later
  summary: Provides functions for the consistent analysis of compositional data (e.g. portions of substances) and positive numbers (e.g. concentrations) in the way proposed by J. Aitchison and V. Pawlowsky-Glahn.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo
