appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: pbuZjTjOzSqlcmmZZcTlKKN+WYJGUJzfov6xsjHa1kz/f8vQ70TZCswCQ7Tvs7wd1vLF3kM/38fKDjigJ7QLB0JuJlmEUjFdWqTDzV6iByQPg218AHFSlJNTfipAh6qNqlvlqqvhWNw0XOeHg/qaVSC0UAPo+wZtODGWIQeo1B3M8LXDlRkwoOu/ffk0/0KvUhIVW0gZ14PvWwbrwjDIxpQ3oD0CipRM0sVo7m1RGIv03kH+00jlcNeq5eAaoPgjjYeXpxGmCV+gtHTEQCaIC/gm76H9LekJ2Ytz4PJBsbve3peRXf7Y2UGEn6Q/MSM1FvaUsGYnWPAYtnUiJHSrF4hdIucPze+xHMF1EReqxCxTDCpj2Zk4Irwz1qvARqC5wysKWG2Vt/qEMU3k569zlM+4Pj2bR1oln5MJMXQPPdsR2gJT+uccu14WwTzQJhpLKq5o0dOPy2cETXtK9MfjZ0CPRfWxJpLJZcinJrua2//7b/CgyuYW/yPaF6mmsRLaEj3I0UlZlfZGy2A+ZlRl+FN1jOPyzgc95LDooOEdqZ157NmPgO4wFETYd1F3tRSyXHPHLW2P5jfD3sDJwRgSd3YA2cC/kTVeZ9c7nJYMhCJH1u/w7v7Gv4mkfSlh8ycUCN2o8mallet+mEvtqoJX+V4eMdpYNiD72XMZGIEtJUk=}
bot:
  automerge: true
